### ISSUE TITLE
v2.0.0 Tracker

### ISSUE THREAD

**Issue by Rayquaza01** [Rayquaza01/authenticator#39]
Tracking for the version 2.0.0 release.

Commits will be made to the [feature](https://github.com/Rayquaza01/authenticator/tree/feature) branch.

The plan is to rewrite the extension in Typescript and make the code more maintainable.

Current planned features:

- [x] Implement TOTP with WebCrypto
- [ ] Implement encryption and decryption with WebCrypto
- [ ] Base 64 encode and decode to Uint8Array
  - might not be necessary if there's a different way to store binary data to browser.storage
- [x] Base 32 decode to Uint8Array
 - Partially done, might want to make writing to the Uint8Array more efficient
- [ ] Remake options page (with drag and drop)
   - [ ] Customizable color schemes?
- [ ] Remake popup page (fixing styling and scrolling issues)
- [ ] Build process
  - Currently have a basic webpack setup, might switch to parcel?

**Comment by wazerstar** [comment]
any news about this?
